# Generated by Django 5.2.6 on 2025-09-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
